version: '3'
services:
  cargo:
    image: ${BUILD_IMAGE:-docker.pkg.github.com/olxgroup-oss/dali/base-rust-image}:latest
    environment: 
        - DALI_HOST=dali
        - HTTP_HOST=http
        - RUSTFLAGS=-C target-feature=-crt-static -L/usr/local/lib -lvips -lgobject-2.0 -lglib-2.0 -lintl
    volumes:
        - ./:/src
    working_dir: /src
    # In the starting commands we remove trust-ad from /etc/resolv.conf because the transitive dependency
    # trust-dns-resolver (v0.18.0-alpha.2) that handles dns queries for actix-http inside actix-connect
    # doesn't support that marker. Currently, this issue has been fixed in trust-dns-resolver (v0.20.0),
    # but no actix-http stable release uses it. Since this issue is happening only during the GitHub pipeline
    # we can remove trust-ad from /etc/resolv.conf inside this docker-compose. After a stable release of actix-http,
    # that has at least v0.20.0 of trust-dns-resolver is released, we can upgrade.
    command: >
            sh -c "tmp_resolv_conf=\"$$(mktemp)\" &&
                sed '/^options /s/\<trust-ad\>//g' /etc/resolv.conf >\"$$tmp_resolv_conf\" &&
                cat \"$$tmp_resolv_conf\" > /etc/resolv.conf &&
                rm -f \"$$tmp_resolv_conf\" &&
                cargo test"