address: 0.0.0.0:7373 # Listen on all network interfaces on port 7373

admin:
    identity: disabled

tls:
    key: private.key    # The KES server TLS private key
    cert: public.crt    # The KES server TLS certificate

policy:
    my-app:
        allow:
            - /v1/key/create/*
            - /v1/key/generate/*
            - /v1/key/decrypt/*
        identities:
            - 30d43740e8a39979aaf015297c9710cee6ef0887199380c6803c38458f8eee96 # Use the identity of your client.crt

keystore:
    fs:
        path: /keys # Choose a directory for the secret keys
