---
name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'  # once daily at 01:30

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          close-issue-message: 'This issue has automatically been closed due to no activities.'
          close-pr-message: 'This pull-request has automatically been closed due to no activities.'
          stale-issue-message: 'This issue has not been updated for a while and will be closed soon.'
          stale-pr-message: 'This pull-request has not been updated for a while and will be closed soon.'
          days-before-stale: 60
          days-before-close: 10
          exempt-all-milestones: true
          exempt-issue-labels: security
          exempt-pr-labels: security
          stale-issue-label: stale
          stale-pr-label: stale
          start-date: 2023-11-07 07:07:07.000
