name: test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: rust:1.59.0-slim
    services:
      backend:
        image: nginx:latest
        options: -v ${{ github.workspace }}/tests/resources/:/usr/share/nginx/html/ --name backend
    steps:
      - uses: actions/checkout@v2
      - name: Restart nginx
        uses: docker://docker
        with:
          args: docker restart backend
      - uses: Swatinem/rust-cache@v1
      - name: Test
        run: |
          apt-get update && apt install -y libvips-dev libvips make curl
          curl http://backend/exif --output /dev/null
          cargo build
          ./target/debug/dali >> /dev/null &
          sleep 5 && curl http://localhost:8080 || true
          HTTP_HOST=backend cargo test
          exit $?
  build_docker_pr:
    runs-on: ubuntu-latest
    needs: ["test"]
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Build and Publish to GPR
        run: |
          sed -i 's/target//g' .dockerignore 
          REVISION=${GITHUB_REF_NAME%\/merge} make docker-publish