name: test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: rust:1.59.0-slim
    services:
      nginx:
        image: nginx:latest
        ports:
          - 9000:80
        options: -v ${{ github.workspace }}/tests/resources/:/usr/share/nginx/html/
    steps:
      - uses: actions/checkout@v2
      - name: libvip
        run: |
          sudo apt-get update
          sudo apt install -y \
            libvips-dev \
            libvips \
            make
      - name: Test
        run: |
          cargo build
          ./target/debug/dali >> /dev/null &
          PID=$!
          cargo test
          RCODE=$?
          kill $PID
          wait $PID
          exit $RCODE