name: test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx:latest
        ports:
          - 9000:80
        options: -v ${{ github.workspace }}/tests/resources/:/usr/share/nginx/html/
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: libvip
        run: |
          sudo apt-get update
          sudo apt install -y \
            libvips-dev \
            libvips \
            make
      - name: Test
        run: |
          cargo build
          ./target/debug/dali >> /dev/null &
          PID=$!
          cargo test
          RCODE=$?
          kill $PID
          wait $PID
          exit $RCODE